version: '3.8'

services:
  # Master / Slaves
  postgres_master:
    image: bitnami/postgresql:14
    container_name: pokemon_master
    ports: ["5432:5432"]
    environment:
      - POSTGRESQL_REPLICATION_MODE=master
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=masterpass
      - POSTGRESQL_DATABASE=pokemon_db
      - POSTGRESQL_REPLICATION_USER=replicator
      - POSTGRESQL_REPLICATION_PASSWORD=replicatorpass
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      - master_data:/bitnami/postgresql
    

  postgres_slave1:
    image: bitnami/postgresql:14
    container_name: pokemon_slave1
    ports: ["5437:5432"]
    environment:
      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=masterpass
      - POSTGRESQL_MASTER_HOST=postgres_master
      - POSTGRESQL_REPLICATION_USER=replicator
      - POSTGRESQL_REPLICATION_PASSWORD=replicatorpass
    volumes:
      - slave1_data:/bitnami/postgresql

  mysql_shard1:
    image: mysql:8
    container_name: mysql_shard1
    ports: ["3308:3306"]
    environment:
      MYSQL_ROOT_PASSWORD: wendy0511
      MYSQL_DATABASE: pokemon_shard1


  mysql_shard2:
    image: mysql:8
    container_name: mysql_shard2
    ports: ["3309:3306"]
    environment:
      MYSQL_ROOT_PASSWORD: wendy0511
      MYSQL_DATABASE: pokemon_shard2


  mysql_pokemon:
    image: mysql:8
    container_name: mysql_pokemon
    ports: ["3307:3306"]
    environment:
      MYSQL_ROOT_PASSWORD: wendy0511
      MYSQL_DATABASE: pokemon_db
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql_data:/var/lib/mysql

  # MongoDB
  mongo:
    image: mongo:6.0
    container_name: pokemon_mongo
    ports: ["27017:27017"]
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo

  # Redis
  redis:
    image: redis:7
    container_name: pokemon_redis
    ports: ["6379:6379"]

  etl_service:
    image: node:20
    container_name: etl_service
    working_dir: /etl
    volumes:
      - ./etl:/etl 
    command: ["tail", "-f", "/dev/null"]  
    depends_on:
      - postgres_master
      - mysql_pokemon
      - mongo
    networks:
      - default

volumes:
  pokedb_data:
  mysql_data:
  mysql_shard1_data:
  mysql_shard2_data:
  master_data:
  slave1_data:
  mongo_data:
